/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.Customer.Customer;
import Business.Customer.CustomerDirectory;
import Business.DB4OUtil.DB4OUtil;
import Business.Enterprise.Enterprise;
import Business.Network.City;
import Business.Organization.Organization;
import Business.SuperMarket;
import Business.Supplier.SupplierDirectory;
import Business.UserAccount.UserAccount;
import UserInterface.SupplierRole.SupplierLoginJPanel;
import UserInterface.CustomerRole.CustomerCheckoutJPanel;
import Business.UserAccount.UserAccountDirectory;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import Business.Organization.CustomerOrganization;
import Business.Role.Role;



/**
 *
 * @author aman9
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    private SuperMarket superMarket;
    private DB4OUtil db4OUtil = DB4OUtil.getInstance();
    private SupplierDirectory supplierDirectory;
    private CustomerDirectory custDir;
    private UserAccountDirectory userAccountDir;
    private Enterprise enterprise;
    private City city;
   
    
       
       
    public MainJFrame() {
        initComponents();
        superMarket = db4OUtil.retrieveSystem();
        custDir=new CustomerDirectory();
        this.setSize(1680,1050);
        supplierDirectory=new SupplierDirectory();
        userAccountDir=new UserAccountDirectory();
        city = new City();
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JSplitPane();
        rightJPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        sysAdminUserTxt = new javax.swing.JTextField();
        sysLoginBtn = new javax.swing.JButton();
        sysLogoutBtn = new javax.swing.JButton();
        passwordField = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        rightJPanel.setBackground(new java.awt.Color(232, 104, 80));
        rightJPanel.setLayout(new java.awt.CardLayout());
        splitPane.setRightComponent(rightJPanel);

        jPanel1.setBackground(new java.awt.Color(88, 116, 152));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Username");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password");

        sysLoginBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sysLoginBtn.setForeground(new java.awt.Color(232, 104, 80));
        sysLoginBtn.setText("Login");
        sysLoginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sysLoginBtnActionPerformed(evt);
            }
        });

        sysLogoutBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        sysLogoutBtn.setForeground(new java.awt.Color(232, 104, 80));
        sysLogoutBtn.setText("Logout");
        sysLogoutBtn.setEnabled(false);
        sysLogoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sysLogoutBtnActionPerformed(evt);
            }
        });

        passwordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(sysLogoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sysLoginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sysAdminUserTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel2)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(sysAdminUserTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(sysLoginBtn)
                .addGap(39, 39, 39)
                .addComponent(sysLogoutBtn)
                .addContainerGap(207, Short.MAX_VALUE))
        );

        splitPane.setLeftComponent(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 628, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sysLoginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sysLoginBtnActionPerformed
        // Get user name
        
        String userName = sysAdminUserTxt.getText();
        
        // Get Password
        char[] passwordCharArray = passwordField.getPassword();
        String password = String.valueOf(passwordCharArray);

        UserAccount userAccount=superMarket.getUserAccountDirectory().authenticateUser(userName, password);
        UserAccount userCustAcc;
        //=superMarket.getUserAccountDirectory().authenticateUser(userName, password);
        
        Enterprise inEnterprise=null;
        Organization inOrganization=null;
        
        if(userAccount==null){
               //Step 2: Go inside each network and check each enterprise
            for(City city:superMarket.getCityList())
            {
                System.out.println("City in for loop Mainframe    " +city);
                //Step 2.a: check against each enterprise
                
                for(Enterprise enterprise:city.getEnterpriseDirectory().getEnterpriseList())
                {
                   
                    userAccount=enterprise.getUserAccountDirectory().authenticateUser(userName, password);
                    //userCustAcc=enterprise.getUserAccountDirectory().authenticateCustUser(userName, password);
                    System.out.println("userAccount in enterprise: "+userAccount);
                    System.out.println("enterprise: "+enterprise);
                    //System.out.println("userCustAcc in enterprise: "+userCustAcc);
                    if(userAccount==null)
                    {
                       //Step 3:check against each organization for each enterprise
                       for(Organization organization:enterprise.getOrganizationDirectory().getOrganizationList())
                       {
                          userAccount=organization.getUserAccountDirectory().authenticateUser(userName, password);
                          //userCustAcc=organization.getUserAccountDirectory().authenticateCustUser(userName, password);
                          System.out.println("userAccount in org: "+userAccount); 
                           System.out.println("organization: "+organization);
                          //System.out.println("userCustAcc in org: "+userCustAcc); 
                          if(userAccount!=null)
                           {
                               inEnterprise=enterprise;
                               inOrganization=organization;
                               break;
                           }
                       }
                        
                    }
                    else
                    {
                       inEnterprise=enterprise;
                       break;
                    }
                    if(inOrganization!=null)
                    {
                        break;
                    }  
                }
                if(inEnterprise!=null){
                    break;
                }
            }
        }
        
       
        if(userAccount==null){
            JOptionPane.showMessageDialog(null, "Invalid credentials");
            return;
        }
        else{
            CardLayout layout=(CardLayout)rightJPanel.getLayout();
            rightJPanel.add("workArea",userAccount.getRole().createWorkArea(rightJPanel, userAccount, inOrganization, inEnterprise, superMarket));
            layout.next(rightJPanel);
        }
        
        
        sysLoginBtn.setEnabled(false);
        sysLogoutBtn.setEnabled(true);
        sysAdminUserTxt.setEnabled(false);
        passwordField.setEnabled(false);
        
    }//GEN-LAST:event_sysLoginBtnActionPerformed

    private void sysLogoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sysLogoutBtnActionPerformed
        // TODO add your handling code here:
        sysLogoutBtn.setEnabled(false);
        sysAdminUserTxt.setEnabled(true);
        passwordField.setEnabled(true);
        sysLoginBtn.setEnabled(true);

        sysAdminUserTxt.setText("");
        passwordField.setText("");

        rightJPanel.removeAll();
        JPanel blankJP = new JPanel();
        rightJPanel.add("blank", blankJP);
        CardLayout crdLyt = (CardLayout) rightJPanel.getLayout();
        crdLyt.next(rightJPanel);
        db4OUtil.storeSystem(superMarket);
    }//GEN-LAST:event_sysLogoutBtnActionPerformed

    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JPanel rightJPanel;
    private javax.swing.JSplitPane splitPane;
    private javax.swing.JTextField sysAdminUserTxt;
    private javax.swing.JButton sysLoginBtn;
    private javax.swing.JButton sysLogoutBtn;
    // End of variables declaration//GEN-END:variables
}
