/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Store;

import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.Organization.StoreInventoryOrganization;
import Business.Organization.StoreManagerOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.StoreInventoryWorkRequest;
import javax.swing.JPanel;

/**
 *
 * @author Administrator
 */
public class StoreInventoryMakeRequestJPanel extends javax.swing.JPanel {

    /**
     * Creates new form StoreInventoryMakeRequestJPanel
     */
    private JPanel rightJPanel;
    private UserAccount userAccount;
    private Enterprise enterprise;
    
    public StoreInventoryMakeRequestJPanel(JPanel rightJPanel,UserAccount account, Enterprise enterprise) {
        initComponents();
        this.rightJPanel=rightJPanel;
        this.userAccount=account;
        this.enterprise=enterprise;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ProductIDTxt = new javax.swing.JTextField();
        submitRequestBtn = new javax.swing.JButton();
        prodNameComboBox = new javax.swing.JComboBox<>();
        quantRequestedSpinner = new javax.swing.JSpinner();

        setBackground(new java.awt.Color(232, 104, 80));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Make Requests to Store Manager");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Product ID");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Request Quantity");

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Product Name");

        submitRequestBtn.setText("Submit Request");
        submitRequestBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitRequestBtnActionPerformed(evt);
            }
        });

        prodNameComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--SELECT--", "EGGS", "ORANGE", "YOGHURT", "CHEESE", "BREAD", "MIXED VEG", "CAPSICUM", "APPLES" }));

        quantRequestedSpinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(submitRequestBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(quantRequestedSpinner)
                            .addComponent(prodNameComboBox, 0, 83, Short.MAX_VALUE)
                            .addComponent(ProductIDTxt))))
                .addContainerGap(189, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ProductIDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(prodNameComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(quantRequestedSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(submitRequestBtn)
                .addGap(111, 111, 111))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void submitRequestBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitRequestBtnActionPerformed
        int ProductId = Integer.parseInt(ProductIDTxt.getText());
        /*String ProductName=ProductNameTxt.getText();
        int requestQuant=Integer.parseInt(RequestQuantitiyTxt.getText());*/
        
        Object q = quantRequestedSpinner.getValue();
        int quantity = Integer.parseInt(q.toString());
        
        StoreInventoryWorkRequest storeInvRequest = new StoreInventoryWorkRequest();
        //storeInvRequest.setMessage(message);
        storeInvRequest.setProductId(ProductId);
        storeInvRequest.setProductName((String)prodNameComboBox.getSelectedItem());
        storeInvRequest.setRequestedQuantity(quantity);
        storeInvRequest.setSender(userAccount);
        storeInvRequest.setStatus("Sent");
        
        Organization org = null;
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
            if (organization instanceof StoreManagerOrganization){
                org = organization;
                break;
            }
        }
        if (org!=null){
            org.getWorkQueue().getWorkRequestList().add(storeInvRequest);
            userAccount.getWorkQueue().getWorkRequestList().add(storeInvRequest);
            System.out.println("Work Queue updated!!");
            System.out.println("org: "+org);
        }
        
        /*ProductIDTxt.setText("");
        ProductNameTxt.setText("");
        RequestQuantitiyTxt.setText("");*/
                
    }//GEN-LAST:event_submitRequestBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ProductIDTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JComboBox<String> prodNameComboBox;
    private javax.swing.JSpinner quantRequestedSpinner;
    private javax.swing.JButton submitRequestBtn;
    // End of variables declaration//GEN-END:variables
}
