/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SupplierRole;

import Business.Enterprise.Enterprise;
import Business.Organization.SupplierOrganization;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import Business.Supplier.Supplier;
import Business.Supplier.SupplierDirectory;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;

/**
 *
 * @author ADMIN
 */
public class SupplierLoginJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SupplierLoginJpanel
     */
    
    private JPanel rightJPanel;
    private Enterprise enterprise;
    //private SupplierOrganization supplierOrg;
    //private SupplierDirectory supplierDirectory;
    int flag;
    private UserAccount userAccount;
    private SupplierOrganization supplierOrg;
    
    public SupplierLoginJPanel(JPanel rightJPanel,UserAccount userAccount,SupplierOrganization supplierOrg, Enterprise enterprise) {
        initComponents();
        this.enterprise=enterprise;
        this.userAccount=userAccount;
        this.supplierOrg=supplierOrg;
        this.rightJPanel=rightJPanel;
        //this.supplierDirectory=supplierDirectory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        supplierUsernameTxtField = new javax.swing.JTextField();
        supplierPwdTxtField = new javax.swing.JTextField();
        supplierLoginBtn = new javax.swing.JButton();
        supplierPwdLabel = new javax.swing.JLabel();
        supplierUsrnmeLabel = new javax.swing.JLabel();
        SupplierJLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(232, 104, 80));

        supplierLoginBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        supplierLoginBtn.setText("Login");
        supplierLoginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supplierLoginBtnActionPerformed(evt);
            }
        });

        supplierPwdLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        supplierPwdLabel.setText("Password");

        supplierUsrnmeLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        supplierUsrnmeLabel.setText("Username:");

        SupplierJLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        SupplierJLabel.setText("Supplier Login !!!!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(265, 265, 265)
                        .addComponent(supplierLoginBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addComponent(SupplierJLabel))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(supplierPwdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(supplierUsrnmeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(supplierUsernameTxtField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(supplierPwdTxtField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(263, 263, 263))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(SupplierJLabel)
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(supplierUsernameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(supplierUsrnmeLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(supplierPwdLabel)
                    .addComponent(supplierPwdTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(86, 86, 86)
                .addComponent(supplierLoginBtn)
                .addContainerGap(93, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void supplierLoginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supplierLoginBtnActionPerformed
        flag=0;
        if(supplierUsernameTxtField.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Supplier username field cannot be empty");
            supplierUsernameTxtField.setText("");
            flag=1;
        }
        
        if(supplierPwdTxtField.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Supplier Password field cannot be empty");
            supplierPwdTxtField.setText("");
            flag=1;
        }
        
        if (flag==0){
            String username=supplierUsernameTxtField.getText();
            String password=supplierPwdTxtField.getText();
            
            for (Supplier s:enterprise.getSupplierDirectory().getSupplierList()){
                System.out.println("s: "+s);
                if(username.equals(s.getSupplierName()) && password.equals(s.getPassword())){
                    SupplierManageProductJPanel smpjp= new SupplierManageProductJPanel(rightJPanel,userAccount,supplierOrg,enterprise);
                    rightJPanel.add("SupplierManageProductJPanel", smpjp);
                    CardLayout layout = (CardLayout) rightJPanel.getLayout();
                    layout.next(rightJPanel); 
                }
//                else{
//                    JOptionPane.showMessageDialog(null, "Invalid login credentials!!");
//                }
            }
        } 
                
        
        
    }//GEN-LAST:event_supplierLoginBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel SupplierJLabel;
    private javax.swing.JButton supplierLoginBtn;
    private javax.swing.JLabel supplierPwdLabel;
    private javax.swing.JTextField supplierPwdTxtField;
    private javax.swing.JTextField supplierUsernameTxtField;
    private javax.swing.JLabel supplierUsrnmeLabel;
    // End of variables declaration//GEN-END:variables
}
