/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.CustomerRole;

import Business.Cart.CartDirectory;
import Business.Customer.CustomerDirectory;
import Business.Network.City;
import Business.SuperMarket;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author ADMIN
 */
public class ChooseProductCategoryJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ChooseProductCategory
     */
    String latitude;
String longitude;
String markerla1;
String markerlo1;
String markerla2;
String markerlo2;
String markerla3;
String markerlo3;
    private JPanel rightJPanel;
    private CustomerDirectory custDir;
    private SuperMarket superMarket;
    private City cityChosen;
    private CartDirectory cartDir;
    private UserAccount user;
    public ChooseProductCategoryJPanel(JPanel rightJPanel,UserAccount user,CustomerDirectory custDir,SuperMarket superMarket,City cityChosen,CartDirectory cartDir ) {
        initComponents();
        
        this.rightJPanel=rightJPanel;
        this.custDir=custDir;
        this.superMarket=superMarket;
        this.cityChosen=cityChosen;
        this.cartDir = cartDir;
        this.user=user;
        
    }
    private void CallApi(String latitude, String longitude, String markerla1, String markerlo1,String markerla2, String markerlo2,String markerla3, String markerlo3){
    JFrame test = new JFrame("Store Locator");
 
        try {
 
            String imageUrl = "https://maps.googleapis.com/maps/api/staticmap?center="
                    + latitude
                    + ","
                    + longitude
                    + "&zoom=12&size=400x400"
                    + "&markers=color:red%7Clabel:E%7C"+markerla1+","+markerlo1+"&markers=color:red%7Clabel:E%7C"+markerla2+","+markerlo2+"&markers=color:red%7Clabel:E%7C"+markerla3+","+markerlo3+"&key=AIzaSyDvm2NiKm_68KOr4EIWRUVD7zDtz1B-k94";
            String destinationFile = "image.jpg";
 
            // read the map image from Google
            // then save it to a local file: image.jpg
            //
            URL url = new URL(imageUrl);
            InputStream is = url.openStream();
            OutputStream os = new FileOutputStream(destinationFile);
 
            byte[] b = new byte[2048];
            int length;
 
            while ((length = is.read(b)) != -1) {
                os.write(b, 0, length);
            }
 
            is.close();
            os.close();
        } catch (IOException e) {
            e.printStackTrace();
            System.exit(1);
        }
 
        // create a GUI component that loads the image: image.jpg
        //
        ImageIcon imageIcon = new ImageIcon((new ImageIcon("image.jpg"))
                .getImage().getScaledInstance(630, 600,
                        java.awt.Image.SCALE_SMOOTH));
        test.add(new JLabel(imageIcon));
 
        // show the GUI window
        test.setVisible(true);
        test.pack();
}
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        milkProductCategoryJPanel = new javax.swing.JButton();
        vegetablesJPanel = new javax.swing.JButton();
        storeLocatorBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(232, 104, 80));

        jLabel1.setBackground(new java.awt.Color(255, 255, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Choose Category");
        jLabel1.setOpaque(true);

        milkProductCategoryJPanel.setBackground(new java.awt.Color(255, 153, 0));
        milkProductCategoryJPanel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        milkProductCategoryJPanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Cow_52px.png"))); // NOI18N
        milkProductCategoryJPanel.setText("Dairy Products");
        milkProductCategoryJPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                milkProductCategoryJPanelActionPerformed(evt);
            }
        });

        vegetablesJPanel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        vegetablesJPanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Vegetarian Mark_64px.png"))); // NOI18N
        vegetablesJPanel.setText("Vegetables and Fruits");
        vegetablesJPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                vegetablesJPanelMouseEntered(evt);
            }
        });
        vegetablesJPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vegetablesJPanelActionPerformed(evt);
            }
        });

        storeLocatorBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Online Store_50px.png"))); // NOI18N
        storeLocatorBtn.setText("Store Locator");
        storeLocatorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                storeLocatorBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(218, 218, 218)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(vegetablesJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(milkProductCategoryJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(storeLocatorBtn)
                        .addGap(13, 13, 13)))
                .addGap(261, 261, 261))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(milkProductCategoryJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(vegetablesJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(storeLocatorBtn)
                .addGap(100, 100, 100))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void milkProductCategoryJPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_milkProductCategoryJPanelActionPerformed
        // TODO add your handling code here:
        
        DisplayDairyProductsJPanel displayMilkProducts= new DisplayDairyProductsJPanel(rightJPanel,user,custDir,superMarket,cityChosen,cartDir);
        rightJPanel.add("Dairy Products JPanel", displayMilkProducts);
        CardLayout layout = (CardLayout) rightJPanel.getLayout();
        layout.next(rightJPanel); 
    }//GEN-LAST:event_milkProductCategoryJPanelActionPerformed

    private void vegetablesJPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vegetablesJPanelActionPerformed
        // TODO add your handling code here:
        
        DisplayVegetablesandFruitsJPanel displayVegetablesJPanel= new DisplayVegetablesandFruitsJPanel(rightJPanel,user,custDir,superMarket,cityChosen,cartDir);
        rightJPanel.add("Display Vegetables Panel", displayVegetablesJPanel);
        CardLayout layout = (CardLayout) rightJPanel.getLayout();
        layout.next(rightJPanel);
        
    }//GEN-LAST:event_vegetablesJPanelActionPerformed

    private void storeLocatorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_storeLocatorBtnActionPerformed
        // TODO add your handling code here:
         System.out.println(cityChosen.getCityName());
        if(cityChosen.getCityName().equals("Boston")){
            latitude = "42.359150";
            longitude = "-71.059439";
            markerla1 = "42.354619";
            markerlo1 = "-71.060163";
            markerla2 = "42.358282";
            markerlo2 = "-71.067990";
            markerla3 = "42.346737";
            markerlo3 = "-71.077152";
            CallApi(latitude , longitude, markerla1, markerlo1,markerla2,markerlo2,markerla3,markerlo3);
        }
        else if(cityChosen.getCityName().equals("New York")){
            latitude = "40.763104";
            longitude = "-73.981679";
            markerla1 = "40.768544";
            markerlo1 = "-73.982954";
            markerla2 = "40.759495";
            markerlo2 = "-73.966144";
            markerla3 = "40.761109";
            markerlo3 = "-73.979517";
             CallApi(latitude , longitude, markerla1, markerlo1,markerla2,markerlo2,markerla3,markerlo3);
        }
        else if(cityChosen.getCityName().equals("Los Angeles")){
            latitude = "34.032495";
            longitude = "-118.485870";
            markerla1 = "34.032947";
            markerlo1 = "-118.494793";
            markerla2 = "34.053620";
            markerlo2 = "-118.467326";
            markerla3 = "34.039084";
            markerlo3 = "-118.481978";
             CallApi(latitude , longitude, markerla1, markerlo1,markerla2,markerlo2,markerla3,markerlo3);
        
    }
        
    }//GEN-LAST:event_storeLocatorBtnActionPerformed

    private void vegetablesJPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vegetablesJPanelMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_vegetablesJPanelMouseEntered


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton milkProductCategoryJPanel;
    private javax.swing.JButton storeLocatorBtn;
    private javax.swing.JButton vegetablesJPanel;
    // End of variables declaration//GEN-END:variables
}
