/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.CustomerRole;

import Business.Cart.CartDirectory;
import Business.Customer.Customer;
import Business.Customer.CustomerDirectory;
import Business.DB4OUtil.DB4OUtil;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Enterprise.EnterpriseDirectory;
import Business.Network.City;
import Business.Organization.CustomerOrganization;
import Business.Organization.Organization;
import Business.Organization.OrganizationDirectory;
import Business.Role.AdminRole;
import Business.Role.CustomerRole;
import Business.UserAccount.UserAccount;
import Business.UserAccount.UserAccountDirectory;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import java.util.Properties;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Transport;
import javax.mail.*;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import Business.Role.Role;
import Business.SuperMarket;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
/**
 *
 * @author Administrator
 */
public class CustomerCheckoutJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CustomerCheckoutJPanel
     */
    private JPanel rightJPanel;
    private CustomerDirectory custDir;
    private SuperMarket superMarket;
    private City cityChoosen;
    private CartDirectory cartList;
    int total;
    int flag;
    private UserAccount user;
    
    public CustomerCheckoutJPanel(JPanel rightJPanel,UserAccount user,CustomerDirectory custDir,SuperMarket superMarket, City cityChoosen, CartDirectory cartList,int total) {
        initComponents();
        
        this.rightJPanel=rightJPanel;
        this.custDir=custDir;
        this.cityChoosen=cityChoosen;
        this.cartList=cartList;
        this.superMarket=superMarket;
        this.total=total;
        this.user=user;
       
        custCity.setText(cityChoosen.getCityName());
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        custName = new javax.swing.JTextField();
        custAddTxtFld = new javax.swing.JTextField();
        custCity = new javax.swing.JTextField();
        custState = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        custEmail = new javax.swing.JTextField();
        custZip = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        paymentBtn = new javax.swing.JButton();
        emailLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(232, 104, 80));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Name*");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Shipping Address*");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("City*");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("State*");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Zip*");

        custName.setDisabledTextColor(new java.awt.Color(153, 153, 153));

        custCity.setEditable(false);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("E-mail*");

        custEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                custEmailKeyTyped(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Checkout");

        paymentBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        paymentBtn.setText("Proceed to Payment");
        paymentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentBtnActionPerformed(evt);
            }
        });

        emailLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addComponent(paymentBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(custState, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(custCity, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(custAddTxtFld, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(custName, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(custEmail, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(custZip, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(emailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(61, 61, 61))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(custName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(emailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(custEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(custAddTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(custCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(custState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(custZip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addComponent(paymentBtn)
                .addGap(91, 91, 91))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    private void paymentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentBtnActionPerformed
        // TODO add your handling code here:
        
        Customer customer= custDir.addCustomer();
        
        //Validate fields should not be empty
        flag=0;
        if(custName.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Customer Name field cannot be empty");
            custName.setText("");       
            flag=1;
        }
        else if(custEmail.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Email field cannot be empty");
            custEmail.setText("");
            flag=1;
        }
        else if(custAddTxtFld.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Address field cannot be empty");
            custAddTxtFld.setText("");       
            flag=1;
        }
        
        else if(custState.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "State cannot be empty");
            custState.setText("");
            flag=1;
        }
        else if (custZip.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Zip cannot be empty");
            custZip.setText("");
            flag=1;
        }
        
        String regexName= "^[A-Za-z\\s]+$";
        Pattern reg = Pattern.compile(regexName);
        Matcher matcher = reg.matcher(custName.getText());
        boolean cName= matcher.matches();
        
        String regex= "^[^(_|\\W)][A-Za-z0-9_]*\\@[A-Za-z]{2,6}+\\.([A-Za-z]{2,3})+$";
        Pattern pa = Pattern.compile(regex);
        Matcher ma = pa.matcher(custEmail.getText());
        boolean cEmail= ma.matches();
        
        String ZipRegex= "^[0-9]{5}$";
        Pattern zip = Pattern.compile(ZipRegex);
        Matcher match = zip.matcher(custZip.getText());
        boolean zipCde= match.matches();
        
        if (cName == false)
        {
            JOptionPane.showMessageDialog(null, "Please enter Name correctly!!");
            flag=1;
        }
        if (cEmail == false)
        {
            JOptionPane.showMessageDialog(null, "Please enter correct Email!!");
            flag=1;
        }
        if (zipCde == false)
        {
            JOptionPane.showMessageDialog(null, "Please enter correct ZipCode!!");
            flag=1;
        }
        
        if (flag==0)
        {
        customer.setCustomerName(custName.getText());
        customer.setEmailId(custEmail.getText());
        customer.setAddress(custAddTxtFld.getText());
        customer.setCity(custCity.getText());
        customer.setState(custState.getText());
        customer.setZipCode(Integer.parseInt(custZip.getText()));
        
        PaymentGatewayJPanel paymentJPanel= new PaymentGatewayJPanel(rightJPanel,user,custDir,superMarket,cityChoosen,cartList,total,customer);
        rightJPanel.add("Payment Panel", paymentJPanel);
        CardLayout layout = (CardLayout) rightJPanel.getLayout();
        layout.next(rightJPanel);
        
        }
    }//GEN-LAST:event_paymentBtnActionPerformed

    private void custEmailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_custEmailKeyTyped
        // TODO add your handling code here:
        emailLabel.setText("Example : abc_def@husky.neu.edu");
    }//GEN-LAST:event_custEmailKeyTyped

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField custAddTxtFld;
    private javax.swing.JTextField custCity;
    private javax.swing.JTextField custEmail;
    private javax.swing.JTextField custName;
    private javax.swing.JTextField custState;
    private javax.swing.JTextField custZip;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton paymentBtn;
    // End of variables declaration//GEN-END:variables
}
