/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.CustomerRole;

import Business.Cart.CartDirectory;
import Business.Customer.CustomerDirectory;
import Business.Network.City;
import Business.Stores.StoreLocationsDirectory;
import Business.SuperMarket;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author ADMIN
 */
public class CustomerSelectCityStoreJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CustomerSelectCityStoreJPanel
     */
    private JPanel rightJPanel;
    private SuperMarket superMarket;
    private CustomerDirectory custDir;
    private CartDirectory cartDir;
    private UserAccount user;
    
    public CustomerSelectCityStoreJPanel(JPanel rightJPanel,UserAccount user,SuperMarket superMarket) {
        initComponents();
        
        this.rightJPanel=rightJPanel;
        this.superMarket=superMarket;
        this.cartDir=new CartDirectory();
        custDir=new CustomerDirectory();
        this.user=user;
        populateCityComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cityComboBox = new javax.swing.JComboBox();
        selectStoreBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(232, 104, 80));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Select Location");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("City");

        cityComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        selectStoreBtn.setText("Submit");
        selectStoreBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectStoreBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(287, 287, 287)
                        .addComponent(selectStoreBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(93, 93, 93)
                        .addComponent(cityComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(322, 322, 322))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cityComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addComponent(selectStoreBtn)
                .addGap(114, 114, 114))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void selectStoreBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectStoreBtnActionPerformed
        // TODO add your handling code here:
        if(cityComboBox.getSelectedItem().equals("--SELECT--"))
        {
            JOptionPane.showMessageDialog(null, "Please select correct value");
            return;
        }
        City cityChoosen= (City) cityComboBox.getSelectedItem();
                
        ChooseProductCategoryJPanel chooseProductCategory= new ChooseProductCategoryJPanel(rightJPanel,user,custDir,superMarket,cityChoosen,cartDir);
        rightJPanel.add("Choose Product Category", chooseProductCategory);
         CardLayout layout = (CardLayout) rightJPanel.getLayout();
        layout.next(rightJPanel);
        
    }//GEN-LAST:event_selectStoreBtnActionPerformed

    private void populateCityComboBox()
    {
        cityComboBox.removeAllItems();
        cityComboBox.addItem("--SELECT--");
        for (City city : superMarket.getCityList())
        {
            cityComboBox.addItem(city);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cityComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton selectStoreBtn;
    // End of variables declaration//GEN-END:variables
}
