/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.CustomerRole;

import Business.Cart.Cart;
import Business.Cart.CartDirectory;
import Business.Customer.CustomerDirectory;
import Business.Network.City;
import Business.SuperMarket;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author ADMIN
 */
public class DisplayVegetablesandFruitsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DisplayProductJPanel
     */
    
    private JPanel rightJPanel;
    private CustomerDirectory custDir;
    private City cityChosen;
    private CartDirectory cartDir;
    private SuperMarket superMarket;
    private UserAccount user;
    public DisplayVegetablesandFruitsJPanel(JPanel rightJPanel,UserAccount user,CustomerDirectory custDir,SuperMarket superMarket, City cityChosen,CartDirectory cartDir) {
        initComponents();
        
        this.custDir=custDir;
        this.rightJPanel=rightJPanel;      
        this.cityChosen = cityChosen;
        this.cartDir = cartDir;
        this.superMarket = superMarket;
        this.user=user;
               
   }

     /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        capsicumJSPinner = new javax.swing.JSpinner();
        orangeJSPinner = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        appleJSPinner = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        mixVegJSPinner = new javax.swing.JSpinner();
        appleBtn = new javax.swing.JButton();
        capsicumBtn = new javax.swing.JButton();
        orangeBtn = new javax.swing.JButton();
        mixVegBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        viewCart = new javax.swing.JButton();

        setBackground(new java.awt.Color(232, 104, 80));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/applesN.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setMaximumSize(new java.awt.Dimension(300, 250));
        jLabel1.setPreferredSize(new java.awt.Dimension(200, 160));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/orangesN.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Vegetables");

        capsicumJSPinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        orangeJSPinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/capcmN.jpg"))); // NOI18N

        appleJSPinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/assortedVeg_new.png"))); // NOI18N

        mixVegJSPinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        appleBtn.setText("Add to Cart");
        appleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appleBtnActionPerformed(evt);
            }
        });

        capsicumBtn.setText("Add to Cart");
        capsicumBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                capsicumBtnActionPerformed(evt);
            }
        });

        orangeBtn.setText("Add to Cart");
        orangeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orangeBtnActionPerformed(evt);
            }
        });

        mixVegBtn.setText("Add to Cart");
        mixVegBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mixVegBtnActionPerformed(evt);
            }
        });

        backBtn.setText("<< Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        jLabel6.setText("Price/lb = $2");

        jLabel7.setText("Price/lb = $2");

        jLabel8.setText("Price/lb = $3");

        jLabel9.setText("Price/lb = $4");

        viewCart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Shopping Cart_50px.png"))); // NOI18N
        viewCart.setText("View Cart >>");
        viewCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewCartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(viewCart, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(224, 224, 224))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(278, 278, 278)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(orangeBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(orangeJSPinner, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(appleBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(appleJSPinner, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(162, 162, 162)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(mixVegBtn)
                                    .addGap(18, 18, 18)
                                    .addComponent(mixVegJSPinner, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(capsicumBtn)
                                .addGap(18, 18, 18)
                                .addComponent(capsicumJSPinner, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(241, 241, 241))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(appleJSPinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(appleBtn)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(orangeJSPinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(orangeBtn)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(capsicumBtn)
                            .addComponent(capsicumJSPinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mixVegJSPinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mixVegBtn)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(viewCart, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(backBtn, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(27, 27, 27))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        
        rightJPanel.remove(this);
        CardLayout layout = (CardLayout) rightJPanel.getLayout();
        layout.previous(rightJPanel);
    }//GEN-LAST:event_backBtnActionPerformed

    private void appleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appleBtnActionPerformed
        // TODO add your handling code here:
        String name = "Apples";
        int price;
       Object q = appleJSPinner.getValue();
        int quantity = Integer.parseInt(q.toString());
        price = 2 * quantity;
        Cart cart = cartDir.addToCart();
        cart.setProductName(name);
        cart.setQuantity(quantity);
        cart.setPrice(price);
    }//GEN-LAST:event_appleBtnActionPerformed

    private void capsicumBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_capsicumBtnActionPerformed
        // TODO add your handling code here:
        String name = "Green Bell Pepper";
        int price;
       Object q = capsicumJSPinner.getValue();
        int quantity = Integer.parseInt(q.toString());
        price = 2 * quantity;
        Cart cart = cartDir.addToCart();
        cart.setProductName(name);
        cart.setQuantity(quantity);
        cart.setPrice(price);
    }//GEN-LAST:event_capsicumBtnActionPerformed

    private void orangeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orangeBtnActionPerformed
        // TODO add your handling code here:
        String name = "Oranges";
        int price;
       Object q = orangeJSPinner.getValue();
        int quantity = Integer.parseInt(q.toString());
        price = 3 * quantity;
        Cart cart = cartDir.addToCart();
        cart.setProductName(name);
        cart.setQuantity(quantity);
        cart.setPrice(price);
    }//GEN-LAST:event_orangeBtnActionPerformed

    private void mixVegBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mixVegBtnActionPerformed
        // TODO add your handling code here:
        String name = "Assorted Vegetables";
        int price;
       Object q = mixVegJSPinner.getValue();
        int quantity = Integer.parseInt(q.toString());
        price = 4 * quantity;
        Cart cart = cartDir.addToCart();
        cart.setProductName(name);
        cart.setQuantity(quantity);
        cart.setPrice(price);
    }//GEN-LAST:event_mixVegBtnActionPerformed

    private void viewCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewCartActionPerformed
        // TODO add your handling code here:
        
        CustomerCartJPanel customerCart= new CustomerCartJPanel(rightJPanel,user,custDir,superMarket,cityChosen,cartDir);
        rightJPanel.add("Customer Cart Panel", customerCart);
        CardLayout layout = (CardLayout) rightJPanel.getLayout();
        layout.next(rightJPanel);
        
    }//GEN-LAST:event_viewCartActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton appleBtn;
    private javax.swing.JSpinner appleJSPinner;
    private javax.swing.JButton backBtn;
    private javax.swing.JButton capsicumBtn;
    private javax.swing.JSpinner capsicumJSPinner;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton mixVegBtn;
    private javax.swing.JSpinner mixVegJSPinner;
    private javax.swing.JButton orangeBtn;
    private javax.swing.JSpinner orangeJSPinner;
    private javax.swing.JButton viewCart;
    // End of variables declaration//GEN-END:variables

   
}
