/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.CustomerRole;

import Business.Cart.Cart;
import Business.Cart.CartDirectory;
import Business.Customer.CustomerDirectory;
import Business.Network.City;
import Business.SuperMarket;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author ADMIN
 */
public class DisplayDairyProductsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DisplayProductJPanel
     */
    private JPanel rightJPanel;
    private CustomerDirectory custDir;
    private City cityChosen;
    private CartDirectory cartDir;
    SuperMarket superMarket;
    private UserAccount user;
    public DisplayDairyProductsJPanel(JPanel rightJPanel,UserAccount user,CustomerDirectory custDir,SuperMarket superMarket, City cityChosen,CartDirectory cartDir) {
        initComponents();
        
        this.custDir=custDir;
        this.rightJPanel=rightJPanel;      
        this.cityChosen = cityChosen;
        this.cartDir = cartDir;
        this.superMarket = superMarket;
        this.user=user;
    }

     /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        yougurtJSpinner = new javax.swing.JSpinner();
        cheeseJSpinner = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        eggsJSPinner = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        breadJSpinner = new javax.swing.JSpinner();
        eggsBtn = new javax.swing.JButton();
        yogurtBtn = new javax.swing.JButton();
        cheeseBtn = new javax.swing.JButton();
        breadBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        viewCart = new javax.swing.JButton();

        setBackground(new java.awt.Color(232, 104, 80));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/eggs.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setMaximumSize(new java.awt.Dimension(300, 250));
        jLabel1.setPreferredSize(new java.awt.Dimension(200, 160));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cheese_dwnld.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Select Milk Products");

        yougurtJSpinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        cheeseJSpinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/yogurt2.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");

        eggsJSPinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bread.jpg"))); // NOI18N

        breadJSpinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        eggsBtn.setText("Add to Cart");
        eggsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eggsBtnActionPerformed(evt);
            }
        });

        yogurtBtn.setText("Add to Cart");
        yogurtBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yogurtBtnActionPerformed(evt);
            }
        });

        cheeseBtn.setText("Add to Cart");
        cheeseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cheeseBtnActionPerformed(evt);
            }
        });

        breadBtn.setText("Add to Cart");
        breadBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                breadBtnActionPerformed(evt);
            }
        });

        backBtn.setText("<< Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        jLabel6.setText("Price/do = $3");

        jLabel7.setText("Price/ea = $4");

        jLabel8.setText("Price/ea = $4");

        jLabel9.setText("Price/ea = $3");

        viewCart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Shopping Cart_50px.png"))); // NOI18N
        viewCart.setText("View Cart >> ");
        viewCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewCartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(eggsBtn)
                                            .addGap(18, 18, 18)
                                            .addComponent(eggsJSPinner, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(cheeseBtn)
                                            .addGap(18, 18, 18)
                                            .addComponent(cheeseJSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(9, 9, 9)))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(85, 85, 85)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(yogurtBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(yougurtJSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(viewCart)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(breadBtn)
                                        .addGap(26, 26, 26)
                                        .addComponent(breadJSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(292, 292, 292)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(42, 42, 42))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yougurtJSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eggsJSPinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eggsBtn)
                    .addComponent(yogurtBtn)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(breadJSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cheeseJSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cheeseBtn)
                    .addComponent(breadBtn)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backBtn)
                    .addComponent(viewCart))
                .addGap(23, 23, 23))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        
        ChooseProductCategoryJPanel chooseProductCat= new ChooseProductCategoryJPanel(rightJPanel,user,custDir,superMarket,cityChosen,cartDir);
        rightJPanel.add("Choose Product Category", chooseProductCat);
        CardLayout layout = (CardLayout) rightJPanel.getLayout();
        layout.next(rightJPanel);
        
    }//GEN-LAST:event_backBtnActionPerformed

    private void eggsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eggsBtnActionPerformed
        // TODO add your handling code here
        String name = "Eggs";
        int price;
       Object q = eggsJSPinner.getValue();
        int quantity = Integer.parseInt(q.toString());
        price = 3 * quantity;
        Cart cart = cartDir.addToCart();
        cart.setProductName(name);
        cart.setQuantity(quantity);
        cart.setPrice(price);
        
    }//GEN-LAST:event_eggsBtnActionPerformed

    private void yogurtBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yogurtBtnActionPerformed
        // TODO add your handling code here:
        String name = "Yogurt";
        int price;
       Object q = yougurtJSpinner.getValue();
        int quantity = Integer.parseInt(q.toString());
        price = 4 * quantity;
        Cart cart = cartDir.addToCart();
        cart.setProductName(name);
        cart.setQuantity(quantity);
        cart.setPrice(price);
    }//GEN-LAST:event_yogurtBtnActionPerformed

    private void cheeseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cheeseBtnActionPerformed
        // TODO add your handling code here:
        String name = "Cheese";
        int price;
       Object q = cheeseJSpinner.getValue();
        int quantity = Integer.parseInt(q.toString());
        price = 4 * quantity;
        Cart cart = cartDir.addToCart();
        cart.setProductName(name);
        cart.setQuantity(quantity);
        cart.setPrice(price);
    }//GEN-LAST:event_cheeseBtnActionPerformed

    private void breadBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_breadBtnActionPerformed
        // TODO add your handling code here:
        String name = "Bread";
        int price;
       Object q = breadJSpinner.getValue();
        int quantity = Integer.parseInt(q.toString());
        price = 3 * quantity;
        Cart cart = cartDir.addToCart();
        cart.setProductName(name);
        cart.setQuantity(quantity);
        cart.setPrice(price);
    }//GEN-LAST:event_breadBtnActionPerformed

    private void viewCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewCartActionPerformed
        // TODO add your handling code here:
        CustomerCartJPanel customerCart= new CustomerCartJPanel(rightJPanel,user,custDir,superMarket,cityChosen,cartDir);
        rightJPanel.add("Customer Cart Panel", customerCart);
        CardLayout layout = (CardLayout) rightJPanel.getLayout();
        layout.next(rightJPanel);
    }//GEN-LAST:event_viewCartActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton breadBtn;
    private javax.swing.JSpinner breadJSpinner;
    private javax.swing.JButton cheeseBtn;
    private javax.swing.JSpinner cheeseJSpinner;
    private javax.swing.JButton eggsBtn;
    private javax.swing.JSpinner eggsJSPinner;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton viewCart;
    private javax.swing.JButton yogurtBtn;
    private javax.swing.JSpinner yougurtJSpinner;
    // End of variables declaration//GEN-END:variables

   
}
