/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.CustomerRole;

import Business.Cart.CartDirectory;
import Business.Customer.Customer;
import Business.Customer.CustomerDirectory;
import Business.Enterprise.CustomerEnterprise;
import Business.Enterprise.Enterprise;
import Business.Enterprise.StoreEnterprise;
import Business.Network.City;
import Business.Organization.CustomerOrganization;
import Business.Organization.DeliveryOrganization;
import Business.Organization.Organization;
import Business.SuperMarket;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.CustomerWorkRequest;
import java.awt.CardLayout;
import java.util.Properties;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.mail.Message;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SpinnerModel;

/**
 *
 * @author ADMIN
 */
public class PaymentGatewayJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PaymentGatewayJPanel
     */
    private JPanel rightJPanel;
    private CustomerDirectory custDir;
    private SuperMarket superMarket;
    private City cityChoosen;
    private CartDirectory cartList;
    int total;
    Customer cust;
    int orderId = 1000;
    private UserAccount user;
    int flag;
    
    
    public PaymentGatewayJPanel(JPanel rightJPanel,UserAccount user,CustomerDirectory custDir,SuperMarket superMarket, City cityChoosen, CartDirectory cartList,int total,Customer customer) {
        initComponents();
        
        this.rightJPanel=rightJPanel;
        this.custDir=custDir;
        this.cityChoosen=cityChoosen;
        this.cartList=cartList;
        this.superMarket=superMarket;
        this.total=total;
        this.cust = customer;
        this.user=user;
        totalJLabel.setText(String.valueOf(total));
        
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        cardNumberTxtFld = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nameOnCrdTxtFld = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cvvTxtFld = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cnfrmPaymntBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        expiryTextField = new javax.swing.JTextField();
        totalJLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        expiryKeyTypeLabel = new javax.swing.JLabel();
        cVVKeyTypeLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setBackground(new java.awt.Color(232, 104, 80));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Card Number");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/PaymentCard.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Name on Card");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("CVV");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Expiry");

        cnfrmPaymntBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cnfrmPaymntBtn.setForeground(new java.awt.Color(204, 0, 102));
        cnfrmPaymntBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Card Payment_50px.png"))); // NOI18N
        cnfrmPaymntBtn.setText("Confirm Payment");
        cnfrmPaymntBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnfrmPaymntBtnActionPerformed(evt);
            }
        });

        backBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        backBtn.setForeground(new java.awt.Color(255, 0, 51));
        backBtn.setText("<<Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        totalJLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        totalJLabel.setForeground(new java.awt.Color(255, 255, 255));
        totalJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalJLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 0), 2, true));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Amount Payable:");

        expiryKeyTypeLabel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                expiryKeyTypeLabelKeyTyped(evt);
            }
        });

        cVVKeyTypeLabel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cVVKeyTypeLabelKeyTyped(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Please enter Details below in order to complete the booking");

        jLabel8.setBackground(new java.awt.Color(255, 255, 0));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 0, 51));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Placing the Order");
        jLabel8.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6)
                    .addComponent(backBtn))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(totalJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nameOnCrdTxtFld)
                                    .addComponent(cardNumberTxtFld)
                                    .addComponent(cvvTxtFld)
                                    .addComponent(expiryTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(32, 32, 32)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cVVKeyTypeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(expiryKeyTypeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cnfrmPaymntBtn)
                        .addGap(71, 71, 71)))
                .addGap(43, 43, 43))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cardNumberTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nameOnCrdTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cvvTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(expiryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(expiryKeyTypeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(totalJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(cVVKeyTypeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cnfrmPaymntBtn)
                    .addComponent(backBtn))
                .addGap(124, 124, 124))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cnfrmPaymntBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnfrmPaymntBtnActionPerformed
        // TODO add your handling code here:
        
        flag=0;
        if(cardNumberTxtFld.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Card Number field cannot be empty");
            cardNumberTxtFld.setText("");       
            flag=1;
        }
        else if(nameOnCrdTxtFld.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Name on Card field cannot be empty");
            nameOnCrdTxtFld.setText("");
            flag=1;
        } 
        else if(cvvTxtFld.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "CVV cannot be empty");
            cvvTxtFld.setText("");       
            flag=1;
        }
        else if(expiryTextField.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Expiry field cannot be empty");
            expiryTextField.setText("");
            flag=1;
        } 
        
        String regex= "^[0-9]{5}$";
        Pattern pa = Pattern.compile(regex);
        Matcher cardNum = pa.matcher(cardNumberTxtFld.getText());
        boolean cd= cardNum.matches();
        
        if (cd == false){
            JOptionPane.showMessageDialog(null, "Please enter correct Card Number!!");
            flag=1;
        }
        
        String cvv= "^[0-9]{3}$";
        Pattern ma = Pattern.compile(cvv);
        Matcher cvvNum = ma.matcher(cvvTxtFld.getText());
        boolean cNum= cvvNum.matches();
        if (cNum == false){
            JOptionPane.showMessageDialog(null, "Please enter 3 digits CVV !!");
            flag=1;
        }
        String expiry= "^[0-9]{2}\\/[0-9]{2}$";
        Pattern date = Pattern.compile(expiry);
        Matcher exDate = date.matcher(expiryTextField.getText());
        boolean expiryDate= exDate.matches();
        if (expiryDate == false){
            JOptionPane.showMessageDialog(null, "Please enter expiry date in MM/YY format!!");
            flag=1;
        }
        
        if (flag==0)
        {
        //Send an email confirming the SignUP
        orderId++;
        Properties props = new Properties();
        props.put("mail.smtp.host", "smtp.gmail.com");
        props.put("mail.smtp.socketFactory.port", "465");
        props.put("mail.smtp.socketFactory.class","javax.net.ssl.SSLSocketFactory");
        props.put("mail.smtp.auth", "true");
         props.put("mail.smtp.port", "465");
        
         Session session = Session.getDefaultInstance(props,
                 new javax.mail.Authenticator(){
                 protected PasswordAuthentication getPasswordAuthentication(){
                     return new PasswordAuthentication("buyeazee@gmail.com","buyeazee@123");
                 }    
                 }
                         
                 );
         try{
             Message message = new MimeMessage(session);
             message.setFrom(new InternetAddress("firzenraj@gmail.com"));
             message.setRecipients(Message.RecipientType.TO, InternetAddress.parse(cust.getEmailId()));
             message.setSubject("Order Confirmation");
             message.setText("Hello "+cust.getCustomerName()+",\nThank You! for shopping with us. Your order has been confirmed with orderId "+orderId+"\n We'll send a confirmation mail once your order is shipped."+"\nWe hope to see you again Soon"+"\nRegards,"+"\nBuy Eazee.");
             Transport.send(message);
             System.out.println("Before call to workQueueCustomer()");
             workQueueCustomer();
         }
         catch(Exception e){
             JOptionPane.showMessageDialog(null, e);
         }
         System.out.println("Outside try");
         workQueueCustomer();
         OrderConfirmationJPanel confirmOrder= new OrderConfirmationJPanel(rightJPanel,custDir,superMarket,cartList,total,cust,orderId);
        rightJPanel.add("Order Confirmation Panel", confirmOrder);
        CardLayout layout = (CardLayout) rightJPanel.getLayout();
        layout.next(rightJPanel);
        }
    }//GEN-LAST:event_cnfrmPaymntBtnActionPerformed

    private void workQueueCustomer(){
        CustomerWorkRequest custRequest = new CustomerWorkRequest();
        
        String custName=cust.getCustomerName();
        String custAddress=cust.getAddress();
        int custOrderID=orderId;
        
        custRequest.setCustomerName(custName);
        custRequest.setCustomerAddress(custAddress);
        custRequest.setCustomerOrerID(custOrderID);
        
        System.out.println("Inside workQueueCustomer()");
        
        Organization org = null;
        for (City c : superMarket.getCityList()){
            System.out.println("c: "+c);
            for (Enterprise e: c.getEnterpriseDirectory().getEnterpriseList()){
                System.out.println("e: "+e);
                if (e instanceof StoreEnterprise){
                    for (Organization organization : e.getOrganizationDirectory().getOrganizationList()){
                        System.out.println("organization: "+organization);
                        if (organization instanceof DeliveryOrganization){
                        org = organization;
                        System.out.println("enterprise.getOrganizationDirectory().getOrganizationList(): "+e.getOrganizationDirectory().getOrganizationList());
                        System.out.println("org: "+org);
                        break;
                    }
                }
            }
        }
        }
        
        if (org!=null){
            org.getWorkQueue().getWorkRequestList().add(custRequest);
            user.getWorkQueue().getWorkRequestList().add(custRequest);
            System.out.println("Work Queue updated for warehouse Inv!!");
            System.out.println("org: "+org);
        }
            
        
    }
    
    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        rightJPanel.remove(this);
        CardLayout layout = (CardLayout) rightJPanel.getLayout();
        layout.previous(rightJPanel);
    }//GEN-LAST:event_backBtnActionPerformed

    private void expiryKeyTypeLabelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_expiryKeyTypeLabelKeyTyped
        // TODO add your handling code here:
        
        expiryKeyTypeLabel.setText("YY/MM format Example: 02/08");
    }//GEN-LAST:event_expiryKeyTypeLabelKeyTyped

    private void cVVKeyTypeLabelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cVVKeyTypeLabelKeyTyped
        // TODO add your handling code here:
        cVVKeyTypeLabel.setText("YY/MM format Example: 02/08");
    }//GEN-LAST:event_cVVKeyTypeLabelKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel cVVKeyTypeLabel;
    private javax.swing.JTextField cardNumberTxtFld;
    private javax.swing.JButton cnfrmPaymntBtn;
    private javax.swing.JTextField cvvTxtFld;
    private javax.swing.JLabel expiryKeyTypeLabel;
    private javax.swing.JTextField expiryTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField nameOnCrdTxtFld;
    private javax.swing.JLabel totalJLabel;
    // End of variables declaration//GEN-END:variables
}
