/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.WarehouseInventory;

import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.Organization.WarehouseInventoryOrganization;
import Business.Organization.WarehouseOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.StoreManagerWorkRequest;
import Business.WorkQueue.WarehouseManagerWorkRequest;
import Business.WorkQueue.WorkRequest;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrator
 */


public class InventoryViewRequestJPanel extends javax.swing.JPanel {

    /**
     * Creates new form InventoryViewRequestJPanel
     */
    
    private JPanel rightJPanel;
    private WarehouseInventoryOrganization warehouseInvOrg;
    private Enterprise enterprise;
    private UserAccount userAccount;
    public InventoryViewRequestJPanel(JPanel rightJPanel,UserAccount userAccount,WarehouseInventoryOrganization warehouseInvOrg,Enterprise enterprise) {
        initComponents();
        this.rightJPanel=rightJPanel;
        this.userAccount=userAccount;
        this.warehouseInvOrg=warehouseInvOrg;
        this.enterprise=enterprise;
        
        System.out.println("Inside InventoryViewRequestJPanel");
        populateTable();
    }

    
    public void populateTable(){
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        
        model.setRowCount(0);
        System.out.println("Inside populateTable of InventoryViewRequestJPanel");
        System.out.println("warehouseInvOrg.getWorkQueue().getWorkRequestList(): "+warehouseInvOrg.getWorkQueue().getWorkRequestList());
        for(WorkRequest request : warehouseInvOrg.getWorkQueue().getWorkRequestList()){
            System.out.println("Inside for of warehouseInvOrg.getWorkQueue().getWorkRequestList()");
            Object[] row = new Object[3];
            row[0] = request;
            //System.out.println("row[0]: "+row[0]);
            /*row[1] = request.getSender().getEmployee().getName();
            row[2] = request.getReceiver() == null ? null : request.getReceiver().getEmployee().getName();
            row[3] = request.getStatus();*/
            row[1]=request.getProductId();
            row[2]=request.getRequestedQuantity();
            
            model.addRow(row);
            
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(232, 104, 80));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Product Name", "Product ID", "Quantity Requested"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Complete Request");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("<< Back ");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setText("View Incoming Request");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(jLabel1)
                .addContainerGap(139, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(30, 30, 30))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int selectedRow = jTable1.getSelectedRow();
        
        System.out.println("Selected Row :"+selectedRow);
        if (selectedRow < 0){
            return;
        }
        else{
            StoreManagerWorkRequest storeMngRequest = (StoreManagerWorkRequest)jTable1.getValueAt(selectedRow, 0);
     
            int prodID=storeMngRequest.getProductId();
            String prodName=storeMngRequest.getProductName();
            int quant=storeMngRequest.getRequestedQuantity();
            
            storeMngRequest.setStatus("Completed");
        
            System.out.println("Request Completed");
            
            WarehouseManagerWorkRequest warehouseMngRequest = new WarehouseManagerWorkRequest();
        
            warehouseMngRequest.setProductId(prodID);
            warehouseMngRequest.setProductName(prodName);
            warehouseMngRequest.setRequestedQuantity(quant);
            
            Organization org = null;    
            for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
                if (organization instanceof WarehouseOrganization){
                    org = organization;
                    System.out.println("enterprise.getOrganizationDirectory().getOrganizationList(): "+enterprise.getOrganizationDirectory().getOrganizationList());
                    System.out.println("org: "+org);
                    break;
                }
            }
            
            if (org!=null){
                org.getWorkQueue().getWorkRequestList().add(warehouseMngRequest);
                userAccount.getWorkQueue().getWorkRequestList().add(warehouseMngRequest);
                System.out.println("Work Queue updated for warehouse Inv!!");
                System.out.println("org: "+org);
            }
        }    
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
