/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.WarehouseInventory;

import Business.Enterprise.Enterprise;
import Business.Organization.WarehouseInventoryOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Administrator
 */
public class WarehouseInventoryJPanel extends javax.swing.JPanel {

    /**
     * Creates new form WarehouseInventoryJPanel
     */
    
    private JPanel rightJPanel;
    private WarehouseInventoryOrganization warehouseInvOrg;
    private Enterprise enterprise;
    private UserAccount userAccount;
    
    public WarehouseInventoryJPanel(JPanel rightJPanel,UserAccount userAccount,WarehouseInventoryOrganization warehouseInvOrg,Enterprise enterprise) {
        initComponents();
        this.rightJPanel=rightJPanel;
        this.enterprise=enterprise;
        this.warehouseInvOrg= warehouseInvOrg;
        this.userAccount= userAccount;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        WarehouseTable = new javax.swing.JTable();
        MakeRequestBtn = new javax.swing.JButton();
        warehouseInventoryLabel = new javax.swing.JLabel();
        viewRequestBtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(232, 104, 80));

        WarehouseTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Product Id", "Product Name", "Quantity Available"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(WarehouseTable);

        MakeRequestBtn.setText("Make Requests");
        MakeRequestBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MakeRequestBtnActionPerformed(evt);
            }
        });

        warehouseInventoryLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        warehouseInventoryLabel.setText("Warehouse Inventory");

        viewRequestBtn.setText("View incoming Request");
        viewRequestBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewRequestBtnActionPerformed(evt);
            }
        });

        jButton1.setText("View Outgoing Request");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(warehouseInventoryLabel)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(viewRequestBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1)
                                .addGap(18, 18, 18)
                                .addComponent(MakeRequestBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jScrollPane1))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(warehouseInventoryLabel)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MakeRequestBtn)
                    .addComponent(viewRequestBtn)
                    .addComponent(jButton1))
                .addGap(58, 58, 58))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void viewRequestBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewRequestBtnActionPerformed
        InventoryViewRequestJPanel ivrjp= new InventoryViewRequestJPanel(rightJPanel,userAccount,warehouseInvOrg,enterprise);
        rightJPanel.add("InventoryViewRequestJPanel", ivrjp);
        CardLayout layout = (CardLayout) rightJPanel.getLayout();
        layout.next(rightJPanel);
    }//GEN-LAST:event_viewRequestBtnActionPerformed

    private void MakeRequestBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MakeRequestBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MakeRequestBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton MakeRequestBtn;
    private javax.swing.JTable WarehouseTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton viewRequestBtn;
    private javax.swing.JLabel warehouseInventoryLabel;
    // End of variables declaration//GEN-END:variables
}
