/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.WarehouseRole;

import Business.Enterprise.Enterprise;
import Business.Enterprise.SupplierEnterprise;
import Business.Network.City;
import Business.Organization.Organization;
import Business.Organization.SupplierOrganization;
import Business.Organization.WarehouseOrganization;
import Business.SuperMarket;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WarehouseManagerWorkRequest;
import javax.swing.JPanel;

/**
 *
 * @author Administrator
 */
public class WarehouseMakeRequestJPanel extends javax.swing.JPanel {

    /**
     * Creates new form WarehouseMakeRequest
     */
    private JPanel rightJPanel;
    private WarehouseOrganization warehouseOrg;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private SuperMarket supermarket;
    
    public WarehouseMakeRequestJPanel(JPanel rightJPanel,UserAccount userAccount,WarehouseOrganization warehouseOrg,Enterprise enterprise,SuperMarket supermarket) {
        initComponents();
        this.rightJPanel=rightJPanel;
        this.enterprise=enterprise;
        this.warehouseOrg= warehouseOrg;
        this.userAccount= userAccount;
        this.supermarket=supermarket;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ProductIDtxt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        makeRequestBtn = new javax.swing.JButton();
        prodNameComboBox = new javax.swing.JComboBox<>();
        quantRequestedSpinner = new javax.swing.JSpinner();

        setBackground(new java.awt.Color(232, 104, 80));

        jLabel1.setText("Product ID");

        jLabel2.setText("Product Name");

        jLabel4.setText("Quantity");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("Make Request to the Supplier");

        ProductIDtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductIDtxtActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setText("<<Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        makeRequestBtn.setBackground(java.awt.Color.white);
        makeRequestBtn.setText("Make Request");
        makeRequestBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                makeRequestBtnActionPerformed(evt);
            }
        });

        prodNameComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--SELECT--", "EGGS", "ORANGE", "YOGHURT", "CHEESE", "BREAD", "MIXED VEG", "CAPSICUM", "APPLES" }));

        quantRequestedSpinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(makeRequestBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ProductIDtxt, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                    .addComponent(prodNameComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(quantRequestedSpinner)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(108, 108, 108)
                                .addComponent(jLabel5)))
                        .addGap(116, 116, 116)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ProductIDtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(prodNameComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(quantRequestedSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(makeRequestBtn))
                .addGap(29, 29, 29))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ProductIDtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductIDtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProductIDtxtActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void makeRequestBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_makeRequestBtnActionPerformed
        int ProductId = Integer.parseInt(ProductIDtxt.getText());
        //String ProductName=ProductNameTxt.getText();
        //String SupplierName=SupplierTxt.getText();
        //int requestQuant=Integer.parseInt(QuantityTxt.getText());
        
        Object q = quantRequestedSpinner.getValue();
        int quantity = Integer.parseInt(q.toString());
        
        WarehouseManagerWorkRequest wareMngRequest = new WarehouseManagerWorkRequest();
        //storeInvRequest.setMessage(message);
        wareMngRequest.setProductId(ProductId);
        wareMngRequest.setProductName((String)prodNameComboBox.getSelectedItem());
        wareMngRequest.setRequestedQuantity(quantity);
        //wareMngRequest.setSupplierName(SupplierName);
        wareMngRequest.setSender(userAccount);
        wareMngRequest.setStatus("Sent");
        
        Organization org = null;
        for (City c : supermarket.getCityList()){
            for (Enterprise e: c.getEnterpriseDirectory().getEnterpriseList()){
                if (e instanceof SupplierEnterprise){
                    for (Organization organization : e.getOrganizationDirectory().getOrganizationList()){
                        if (organization instanceof SupplierOrganization){
                        org = organization;
                        System.out.println("enterprise.getOrganizationDirectory().getOrganizationList(): "+e.getOrganizationDirectory().getOrganizationList());
                        System.out.println("org: "+org);
                        break;
                    }
                }
            }
        }
        }
        
        if (org!=null){
            org.getWorkQueue().getWorkRequestList().add(wareMngRequest);
            userAccount.getWorkQueue().getWorkRequestList().add(wareMngRequest);
            System.out.println("Work Queue updated!!");
            System.out.println("org: "+org);
        }
        /*ProductIDtxt.setText("");
        ProductNameTxt.setText("");
        QuantityTxt.setText("");*/
    }//GEN-LAST:event_makeRequestBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ProductIDtxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton makeRequestBtn;
    private javax.swing.JComboBox<String> prodNameComboBox;
    private javax.swing.JSpinner quantRequestedSpinner;
    // End of variables declaration//GEN-END:variables
}
