/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.WarehouseRole;

import Business.Enterprise.Enterprise;
import Business.Organization.WarehouseOrganization;
import Business.SuperMarket;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WarehouseManagerWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrator
 */
public class WarehouseJPanel extends javax.swing.JPanel {

    /**
     * Creates new form WarehouseJPanel
     */
    private JPanel rightJPanel;
    private WarehouseOrganization warehouseOrg;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private SuperMarket supermarket;
    
    public WarehouseJPanel(JPanel rightJPanel,UserAccount userAccount,WarehouseOrganization warehouseOrg,Enterprise enterprise, SuperMarket supermarket) {
        initComponents();
        this.rightJPanel=rightJPanel;
        this.enterprise=enterprise;
        this.warehouseOrg= warehouseOrg;
        this.userAccount= userAccount;
        this.supermarket=supermarket;
        
        System.out.println("Inside WarehouseJPanel");
        populateTable();
    }
    
    public void populateTable(){
        DefaultTableModel model = (DefaultTableModel)requestJTable.getModel();
        
        model.setRowCount(0);
        System.out.println("Inside populateTable of WarehouseJPanel");
        System.out.println("warehouseOrg.getWorkQueue().getWorkRequestList(): "+warehouseOrg.getWorkQueue().getWorkRequestList());
        for(WorkRequest request : warehouseOrg.getWorkQueue().getWorkRequestList()){
            System.out.println("Inside for of warehouseOrg.getWorkQueue().getWorkRequestList()");
            Object[] row = new Object[3];
            row[0] = request;
            //System.out.println("row[0]: "+row[0]);
            /*row[1] = request.getSender().getEmployee().getName();
            row[2] = request.getReceiver() == null ? null : request.getReceiver().getEmployee().getName();
            row[3] = request.getStatus();*/
            row[1]=request.getProductId();
            row[2]=request.getRequestedQuantity();
            
            model.addRow(row);
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        completeRequestBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        requestJTable = new javax.swing.JTable();
        makeRequestBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(232, 104, 80));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("View Incoming Request");

        backBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        backBtn.setText("<< Back ");

        completeRequestBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        completeRequestBtn.setText("Complete Request");
        completeRequestBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                completeRequestBtnActionPerformed(evt);
            }
        });

        requestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Product Name", "Product ID", "Quantity"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(requestJTable);

        makeRequestBtn.setText("Make Request");
        makeRequestBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                makeRequestBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(268, 268, 268)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(59, 59, 59)
                            .addComponent(backBtn)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(makeRequestBtn)
                            .addGap(112, 112, 112)
                            .addComponent(completeRequestBtn))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(117, 117, 117)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(129, 129, 129))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(129, 129, 129)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backBtn)
                    .addComponent(completeRequestBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(makeRequestBtn))
                .addGap(51, 51, 51))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void completeRequestBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_completeRequestBtnActionPerformed
        int selectedRow = requestJTable.getSelectedRow();
        
        System.out.println("Selected Row :"+selectedRow);
        if (selectedRow < 0){
            return;
        }
        else{
            WarehouseManagerWorkRequest warehouseMngRequest = (WarehouseManagerWorkRequest)requestJTable.getValueAt(selectedRow, 0);
     
//            int prodID=storeMngRequest.getProductId();
//            String prodName=storeMngRequest.getProductName();
//            int quant=storeMngRequest.getRequestedQuantity();
            
            warehouseMngRequest.setStatus("Completed");
        
            System.out.println("Request Completed");
            
            JOptionPane.showMessageDialog(null, "Request Accepted by the Warehouse Manager");
        }
    }//GEN-LAST:event_completeRequestBtnActionPerformed

    private void makeRequestBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_makeRequestBtnActionPerformed
        WarehouseMakeRequestJPanel ivrjp= new WarehouseMakeRequestJPanel(rightJPanel,userAccount,warehouseOrg,enterprise,supermarket);
        rightJPanel.add("InventoryViewRequestJPanel", ivrjp);
        CardLayout layout = (CardLayout) rightJPanel.getLayout();
        layout.next(rightJPanel);
    }//GEN-LAST:event_makeRequestBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton completeRequestBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton makeRequestBtn;
    private javax.swing.JTable requestJTable;
    // End of variables declaration//GEN-END:variables
}
